spring.datasource.url=jdbc:postgresql://${DB_HOST:gondola.proxy.rlwy.net}:${DB_PORT:46266}/${DB_NAME:railway}?sslmode=${DB_SSLMODE:require}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:REDACTED_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

